-- SCV1-T01: estado persistente do walking skeleton do ConsultantGraph.
create table if not exists public.consultant_sessions (
  id uuid primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  state jsonb not null,
  revision integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consultant_turns (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.consultant_sessions(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  idempotency_key text not null,
  response jsonb not null,
  revision integer not null,
  created_at timestamptz not null default now(),
  unique (session_id, idempotency_key),
  unique (workspace_id, idempotency_key)
);

create index if not exists consultant_sessions_workspace_updated_idx
  on public.consultant_sessions (workspace_id, updated_at desc);

alter table public.consultant_sessions enable row level security;
alter table public.consultant_turns enable row level security;

drop policy if exists consultant_sessions_select_own on public.consultant_sessions;
create policy consultant_sessions_select_own on public.consultant_sessions
  for select using (workspace_id in (select id from public.workspaces where user_id = auth.uid()));

drop policy if exists consultant_sessions_insert_own on public.consultant_sessions;
create policy consultant_sessions_insert_own on public.consultant_sessions
  for insert with check (workspace_id in (select id from public.workspaces where user_id = auth.uid()));

drop policy if exists consultant_sessions_update_own on public.consultant_sessions;
create policy consultant_sessions_update_own on public.consultant_sessions
  for update using (workspace_id in (select id from public.workspaces where user_id = auth.uid()))
  with check (workspace_id in (select id from public.workspaces where user_id = auth.uid()));

drop policy if exists consultant_sessions_delete_own on public.consultant_sessions;
create policy consultant_sessions_delete_own on public.consultant_sessions
  for delete using (workspace_id in (select id from public.workspaces where user_id = auth.uid()));

drop policy if exists consultant_turns_select_own on public.consultant_turns;
create policy consultant_turns_select_own on public.consultant_turns
  for select using (workspace_id in (select id from public.workspaces where user_id = auth.uid()));

drop policy if exists consultant_turns_insert_own on public.consultant_turns;
create policy consultant_turns_insert_own on public.consultant_turns
  for insert with check (workspace_id in (select id from public.workspaces where user_id = auth.uid()));
